version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/x-cyber
      - JWT_SECRET=your_jwt_secret
      - PORT=3000
    depends_on:
      - mongo
    volumes:
      - ./server:/app/server
      - ./client:/app/client
      - ./certs:/etc/nginx/certs

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: